# Working with NumPy
## Jackson Gawarecki
### Version: 1
#### DS160 

In [2]:
import numpy as np

# A)

In [3]:
arr1=np.array([[10,20],[30,40]])
print(arr1)

[[10 20]
 [30 40]]


In [4]:
np.square(arr1)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [5]:
arr1+100

array([[110, 120],
       [130, 140]])

In [6]:
np.add(arr1,100)

array([[110, 120],
       [130, 140]])

In [7]:
arr1*5

array([[ 50, 100],
       [150, 200]])

In [8]:
np.multiply(arr1,5)

array([[ 50, 100],
       [150, 200]])

In [9]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

# B)

In [10]:
import random
arr2=np.arange(3,28,3).reshape(3,3)
arr2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [14]:
arr3=np.linspace(10,20,9)
y=arr3.reshape(3,3)
y

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [16]:
np.multiply(arr2,y)

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

# C)

In [24]:
process1=np.load('process1.npy')
process1

array([[52, 12, 81,  0, 58]])

In [25]:
process2=np.load('process2.npy')
process2

array([[96,  4, 61, 16, 43]])

In [26]:
process3=np.load('process3.npy')
process3

array([[38, 96, 45, 17, 58]])

In [27]:
process4=np.load('process4.npy')
process4

array([[97, 21, 22, 25,  6]])

In [28]:
process5=np.load('process5.npy')
process5

array([[77,  6, 19,  2, 74]])

In [30]:
np.vstack((process1,process2,process3,process4,process5))

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])